name: CI

on:
  pull_request:
    branches: [master]
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "daws.json"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install mingw toolchain
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          target: ${{ matrix.target }}
          components: rustfmt, clippy
          rustflags: ""
          cache-shared-key: ci-${{ matrix.os }}

      - name: Format check
        if: matrix.os == 'windows-latest'
        run: cargo fmt --all -- --check

      - name: Clippy
        env:
          TARGET: ${{ matrix.target }}
        shell: bash
        run: cargo clippy --all-targets --target "$TARGET" -- -D warnings

      - name: Build
        env:
          TARGET: ${{ matrix.target }}
        shell: bash
        run: cargo build --release --target "$TARGET"

      - name: Test
        run: cargo test
